# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../tools/impeller.gni")

impeller_component("ohos") {
  sources = [
    "native_buffer.cc",
    "native_buffer.h",
    "native_window.cc",
    "native_window.h",
  ]

  public_deps = [
    "../../base",
    "../../geometry",
    "//flutter/fml",
  ]
}
