# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//flutter/common/config.gni")
import("//flutter/testing/testing.gni")

source_set("napi") {
  sources = [
    "platform_view_ohos_napi.cc",
    "platform_view_ohos_napi.h",
  ]

  public_configs = [ "//flutter:config" ]

  deps = [
    "//flutter/flow",
    "//flutter/fml",
    "//flutter/lib/ui",
    "//flutter/shell/platform/ohos/surface:native_window",
    "//flutter/skia",
  ]
}
