# Copyright (c) 2023 Hunan OpenValley Digital Industry Development Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/config/ohos/config.gni")
import("//build/toolchain/clang.gni")
import("//flutter/build/bin_to_obj.gni")
import("//flutter/build/zip_bundle.gni")
import("//flutter/common/config.gni")
import("//flutter/shell/gpu/gpu.gni")
import("//flutter/shell/version/version.gni")

shell_gpu_configuration("ohos_gpu_configuration") {
  enable_software = true
  enable_gl = true
  enable_vulkan = true
  enable_metal = false
}

group("ohos") {
  deps = [
    ":flutter_har_zip",
    ":flutter_shell_native",
    ":ohos_symbols",
  ]
  if (target_cpu != "x86") {
    deps += [ ":gen_snapshot" ]
  }
}

source_set("image_generator") {
  sources = [
    "ohos_image_generator.cc",
    "ohos_image_generator.h",
  ]

  deps = [
    "//flutter/fml",
    "//flutter/lib/ui:ui",
    "//flutter/skia",
  ]

  libs = [
    "image_source",
    "pixelmap",
  ]
}

shared_library("flutter_shell_native") {
  inputs = [ "ohos_exports.lst" ]
  output_name = "flutter"
  deps = [ ":flutter_shell_native_src" ]
  ldflags = [ "-Wl,--version-script=" +
              rebase_path("ohos_exports.lst", root_build_dir) ]
}

bin_to_assembly("icudtl_asm") {
  deps = []
  input = "//flutter/third_party/icu/flutter/icudtl.dat"
  symbol = "_binary_icudtl_dat_start"
  size_symbol = "_binary_icudtl_dat_size"
  executable = false
}

source_set("flutter_shell_native_src") {
  visibility = [ ":*" ]

  sources = [
    "flutter_main.cc",
    "flutter_main.h",
    "library_loader.cc",
    "ohos_asset_provider.cc",
    "ohos_asset_provider.h",
    "ohos_context_gl_impeller.cc",
    "ohos_context_gl_impeller.h",
    "ohos_context_gl_skia.cc",
    "ohos_context_gl_skia.h",
    "ohos_context_vulkan_impeller.cc",
    "ohos_context_vulkan_impeller.h",
    "ohos_display.cc",
    "ohos_display.h",
    "ohos_egl_surface.cc",
    "ohos_egl_surface.h",
    "ohos_environment_gl.cc",
    "ohos_environment_gl.h",
    "ohos_shell_holder.cc",
    "ohos_shell_holder.h",
    "ohos_surface_gl_impeller.cc",
    "ohos_surface_gl_impeller.h",
    "ohos_surface_gl_skia.cc",
    "ohos_surface_gl_skia.h",
    "ohos_surface_software.cc",
    "ohos_surface_software.h",
    "ohos_surface_vulkan_impeller.cc",
    "ohos_surface_vulkan_impeller.h",
    "platform_message_handler_ohos.cc",
    "platform_message_handler_ohos.h",
    "platform_message_response_ohos.cc",
    "platform_message_response_ohos.h",
    "platform_view_ohos.cc",
    "platform_view_ohos.h",
    "platform_view_ohos_napi_impl.cc",
    "platform_view_ohos_napi_impl.h",
    "surface_texture_external_texture.cc",
    "surface_texture_external_texture.h",
    "surface_texture_external_texture_gl.cc",
    "surface_texture_external_texture_gl.h",
    "vsync_waiter_ohos.cc",
    "vsync_waiter_ohos.h",
  ]

  sources += get_target_outputs(":icudtl_asm")

  public_deps = [
    ":icudtl_asm",
    ":image_generator",
    ":ohos_gpu_configuration",
    "//flutter/assets",
    "//flutter/common",
    "//flutter/common/graphics",
    "//flutter/flow",
    "//flutter/fml",
    "//flutter/impeller",
    "//flutter/impeller/toolkit/egl",
    "//flutter/impeller/toolkit/gles",
    "//flutter/impeller/toolkit/ohos",
    "//flutter/lib/ui",
    "//flutter/runtime",
    "//flutter/runtime:libdart",
    "//flutter/shell/common",
    "//flutter/shell/platform/ohos/context",
    "//flutter/shell/platform/ohos/napi",
    "//flutter/shell/platform/ohos/surface",
    "//flutter/shell/platform/ohos/surface:native_window",
    "//flutter/skia",
    "//flutter/third_party/txt",
    "//flutter/vulkan",
  ]

  public_configs = [ "//flutter:config" ]

  defines = [
    "OHOS_PLATFORM",  # Used in ohos EGL
  ]

  libs = [
    "ace_napi.z",
    "ace_ndk.z",  # Used in ohos XComponentAdapter
    "EGL",
    "GLESv3",
    "native_buffer",
    "native_display_manager",
    "native_image",
    "native_vsync",
    "native_window",
    "qos",
    "rawfile.z",
  ]
}

declare_args() {
  ohos_zip_archive_dir = "ohos-$target_cpu"
  if (flutter_runtime_mode != "debug") {
    ohos_zip_archive_dir += "-$flutter_runtime_mode"
  }
}

ohos_arkts_sources = [
  "flutter_embedding/AppScope/app.json5",
  "flutter_embedding/AppScope/resources/base/element/string.json",
  "flutter_embedding/AppScope/resources/base/media/app_icon.png",
  "flutter_embedding/flutter/src/main/cpp/types/libflutter/index.d.ets",
  "flutter_embedding/flutter/src/main/cpp/types/libflutter/oh-package.json5",

  # "flutter_embedding/flutter/src/main/ets/app/FlutterActivity.ets",
  # "flutter_embedding/flutter/src/main/ets/app/FlutterActivityDelegate.ets",
  # "flutter_embedding/flutter/src/main/ets/app/FlutterActivityEvents.ets",
  # "flutter_embedding/flutter/src/main/ets/app/FlutterApplication.ets",
  # "flutter_embedding/flutter/src/main/ets/app/FlutterFragmentActivity.ets",
  # "flutter_embedding/flutter/src/main/ets/app/FlutterPlayStoreSplitApplication.ets",

  "flutter_embedding/flutter/src/main/ets/embedding/engine/dart/DartExecutor.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/dart/DartMessenger.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/dart/PlatformMessageHandler.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/dart/PlatformTaskQueue.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/deferredcomponents/DeferredComponentManager.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/deferredcomponents/PlayStoreDeferredComponentManager.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/loader/ApplicationInfoLoader.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/loader/FlutterApplicationInfo.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/loader/FlutterLoader.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/loader/ResourceExtractor.ets",

  "flutter_embedding/flutter/src/main/ets/embedding/engine/mutatorsstack/FlutterMutatorView.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/mutatorsstack/FlutterMutatorsStack.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/FlutterPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/PluginRegistry.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/ability/AbilityAware.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/ability/AbilityControlSurface.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/ability/AbilityPluginBinding.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverAware.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverControlSurface.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverPluginBinding.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/contentprovider/ContentProviderAware.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/contentprovider/ContentProviderControlSurface.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/contentprovider/ContentProviderPluginBinding.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/lifecycle/HiddenLifecycleReference.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/service/ServiceAware.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/service/ServiceControlSurface.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/service/ServicePluginBinding.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/shim/ShimPluginRegistry.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/shim/ShimRegistrar.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/plugins/util/GeneratedPluginRegister.ets",

  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterEngine.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterEngineCache.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterEngineConnectionRegistry.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterEngineGroup.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterEngineGroupCache.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterNAPI.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterOverlaySurface.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/FlutterShellArgs.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/renderer/FlutterRenderer.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/renderer/FlutterUiDisplayListener.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/renderer/RenderSurface.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/renderer/SurfaceTextureSurfaceProducer.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/renderer/SurfaceTextureWrapper.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/AccessibilityChannel.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/BackGestureChannel.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/DeferredComponentChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/KeyEventChannel.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/KeyboardChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/LifecycleChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/LocalizationChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/MouseCursorChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/NavigationChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/PlatformChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/PlatformViewsChannel.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/ProcessTextChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/RestorationChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/SettingsChannel.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/SpellCheckChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/SystemChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/systemchannels/TextInputChannel.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/engine/workers/PlatformChannelWorker.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/EmbeddingNodeController.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/ExclusiveAppComponent.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterAbility.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterAbilityAndEntryDelegate.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterAbilityLaunchConfigs.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterEngineConfigurator.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterEngineProvider.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterEntry.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterManager.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterPage.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/FlutterView.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/KeyChannelResponder.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/KeyData.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/KeyEmbedderResponder.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/KeyboardManager.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/KeyboardMap.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/OhosTouchProcessor.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/PlatformViewInfo.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/TouchEventTracker.ets",

  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/RenderMode.ets",
  # "flutter_embedding/flutter/src/main/ets/embedding/ohos/TransparencyMode.ets",
  "flutter_embedding/flutter/src/main/ets/embedding/ohos/WindowInfoRepositoryCallbackAdapterWrapper.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/Any.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/common/AbilityLifecycleListener.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/BackgroundBasicMessageChannel.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/BackgroundMethodChannel.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/BasicMessageChannel.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/BinaryCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/BinaryMessenger.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/common/ErrorLogResult.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/EventChannel.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/FlutterException.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/JSONMessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/JSONMethodCodec.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/common/JSONUtil.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/MessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/MethodCall.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/MethodChannel.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/MethodCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/PluginRegistry.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableBinaryCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableBinaryMessageHandler.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableJSONMessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableJSONMethodCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableMessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableMessageHandler.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableMethodCallHandler.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableMethodCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableStandardMessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableStandardMethodCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/SendableStringCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/StandardMessageCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/StandardMethodCodec.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/common/StringCodec.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/editing/FlutterTextUtils.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/editing/ImeSyncDeferringInsetsCallback.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/editing/InputConnectionAdaptor.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/editing/ListenableEditingState.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/editing/SpellCheckPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/editing/TextEditingDelta.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/editing/TextInputPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/localization/LocalizationPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/mouse/MouseCursorPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/AccessibilityEventsDelegate.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/platform/ImageReaderPlatformViewRenderTarget.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/CustomTouchEvent.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformOverlayView.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformPlugin.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformView.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewFactory.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewRegistry.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewRegistryImpl.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewWrapper.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewRenderTarget.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewsAccessibilityDelegate.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/PlatformViewsController.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/RawPointerCoord.ets",
  "flutter_embedding/flutter/src/main/ets/plugin/platform/RootDvModelManager.ets",

  # "flutter_embedding/flutter/src/main/ets/plugin/platform/SingleViewFakeWindowViewGroup.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/SingleViewPresentation.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/SingleViewWindowManager.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/SurfaceProducerPlatformViewRenderTarget.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/SurfaceTexturePlatformViewRenderTarget.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/VirtualDisplayController.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/platform/WindowManagerHandler.ets",
  # "flutter_embedding/flutter/src/main/ets/plugin/text/ProcessTextPlugin.ets",

  "flutter_embedding/flutter/src/main/ets/plugin/PlatformPlugin.ets",

  # "flutter_embedding/flutter/src/main/ets/util/HandlerCompat.ets",
  "flutter_embedding/flutter/src/main/ets/util/ByteBuffer.ets",
  "flutter_embedding/flutter/src/main/ets/util/Log.ets",
  "flutter_embedding/flutter/src/main/ets/util/MessageChannelUtils.ets",
  "flutter_embedding/flutter/src/main/ets/util/PathUtils.ets",
  "flutter_embedding/flutter/src/main/ets/util/StringUtils.ets",
  "flutter_embedding/flutter/src/main/ets/util/ToolUtils.ets",

  # "flutter_embedding/flutter/src/main/ets/util/Preconditions.ets",
  # "flutter_embedding/flutter/src/main/ets/util/Predicate.ets",
  "flutter_embedding/flutter/src/main/ets/util/TraceSection.ets",

  # "flutter_embedding/flutter/src/main/ets/util/ViewUtils.ets",

  "flutter_embedding/flutter/src/main/ets/view/AccessibilityBridge.ets",
  "flutter_embedding/flutter/src/main/ets/view/DynamicView/dynamicView.ets",
  "flutter_embedding/flutter/src/main/ets/view/DynamicView/dynamicViewJson.ets",

  # "flutter_embedding/flutter/src/main/ets/view/AccessibilityViewEmbedder.ets",
  "flutter_embedding/flutter/src/main/ets/view/FlutterCallbackInformation.ets",

  # "flutter_embedding/flutter/src/main/ets/view/FlutterMain.ets",
  # "flutter_embedding/flutter/src/main/ets/view/FlutterNativeView.ets",
  "flutter_embedding/flutter/src/main/ets/view/FlutterRunArguments.ets",
  "flutter_embedding/flutter/src/main/ets/view/FlutterView.ets",
  "flutter_embedding/flutter/src/main/ets/view/TextureRegistry.ets",

  # "flutter_embedding/flutter/src/main/ets/view/VsyncWaiter.ets",

  "flutter_embedding/flutter/src/main/ets/FlutterInjector.ets",

  # "flutter_embedding/flutter/src/main/ets/Log.ets",

  "flutter_embedding/.gitignore",
  "flutter_embedding/build-profile.json5",
  "flutter_embedding/flutter/.gitignore",
  "flutter_embedding/flutter/build-profile.json5",
  "flutter_embedding/flutter/consumer-rules.txt",
  "flutter_embedding/flutter/hvigorfile.ts",
  "flutter_embedding/flutter/index.ets",
  "flutter_embedding/flutter/oh-package.json5",
  "flutter_embedding/flutter/src/main/module.json5",
  "flutter_embedding/hvigor/hvigor-config.json5",
  "flutter_embedding/hvigorfile.ts",
  "flutter_embedding/oh-package.json5",
]

action("ohos_har") {
  script = "//build/ohos/create_flutter_har.py"

  if (stripped_symbols) {
    engine_library = "libflutter.so"
  } else {
    engine_library = "so.unstripped/libflutter.so"
  }

  sources = ohos_arkts_sources

  inputs = [ "$root_build_dir/$engine_library" ]

  outputs = [ "$root_build_dir/flutter.har" ]

  args = [
           "--build_dir",
           "./obj/ohos",
           "--build_type",
           flutter_runtime_mode,
           "--output",
           rebase_path("flutter.har", root_build_dir, root_build_dir),
           "--native_lib",
           rebase_path("$engine_library", root_build_dir, root_build_dir),
           "--ohos_abi",
           ohos_app_abi,
           "--source_dir",
           rebase_path("."),
           "--source_files",
         ] + ohos_arkts_sources

  deps = [ ":flutter_shell_native" ]

  if (flutter_runtime_mode == "profile") {
    deps += [ "//flutter/shell/vmservice:vmservice_snapshot" ]
    args += [
      "--native_lib",
      rebase_path(
          "$root_gen_dir/flutter/shell/vmservice/ohos/libs/$ohos_app_abi/libvmservice_snapshot.so",
          root_build_dir,
          root_build_dir),
    ]
  }
}

zip_bundle("flutter_har_zip") {
  output = "$ohos_zip_archive_dir/artifacts.zip"
  files = [
    {
      source = "$root_build_dir/flutter.har"
      destination = "flutter.har"
    },
  ]

  deps = [ ":ohos_har" ]
}

zip_bundle("ohos_symbols") {
  output = "$ohos_zip_archive_dir/symbols.zip"
  files = [
    {
      source = "$root_build_dir/so.unstripped/libflutter.so"
      destination = "libflutter.so"
    },
  ]

  deps = [ ":flutter_shell_native" ]
}

generated_file("ohos_entitlement_config") {
  outputs = [ "$target_gen_dir/ohos_entitlements.txt" ]
  contents = [ "gen_snapshot" ]
  deps = []
}

if (target_cpu != "x86") {
  zip_bundle("gen_snapshot") {
    gen_snapshot_bin = "gen_snapshot"
    gen_snapshot_out_dir = get_label_info(
            "//flutter/third_party/dart/runtime/bin:gen_snapshot($host_toolchain)",
            "root_out_dir")
    gen_snapshot_path = rebase_path("$gen_snapshot_out_dir/$gen_snapshot_bin")

    if (host_os == "linux") {
      output = "$ohos_zip_archive_dir/linux-x64.zip"
    } else if (host_os == "mac") {
      output = "$ohos_zip_archive_dir/darwin-x64.zip"
    } else if (host_os == "win") {
      output = "$ohos_zip_archive_dir/windows-x64.zip"
      gen_snapshot_bin = "gen_snapshot.exe"
      gen_snapshot_path = rebase_path("$root_out_dir/$gen_snapshot_bin")
    }

    files = [
      {
        source = gen_snapshot_path
        destination = gen_snapshot_bin
      },
    ]

    deps = [
      "//flutter/third_party/dart/runtime/bin:gen_snapshot($host_toolchain)",
    ]
  }

  # TODO(godofredoc): Remove gen_snapshot and rename new_gen_snapshot when v2 migration is complete.
  # BUG: https://github.com/flutter/flutter/issues/105351
  zip_bundle("new_gen_snapshot") {
    gen_snapshot_bin = "gen_snapshot"
    gen_snapshot_out_dir = get_label_info(
            "//flutter/third_party/dart/runtime/bin:gen_snapshot($host_toolchain)",
            "root_out_dir")
    gen_snapshot_path = rebase_path("$gen_snapshot_out_dir/$gen_snapshot_bin")

    if (host_os == "linux") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/linux-x64.zip"
    } else if (host_os == "mac") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/darwin-x64.zip"
    } else if (host_os == "win") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/windows-x64.zip"
      gen_snapshot_bin = "gen_snapshot.exe"
      gen_snapshot_path = rebase_path("$root_out_dir/$gen_snapshot_bin")
    }

    files = [
      {
        source = gen_snapshot_path
        destination = gen_snapshot_bin
      },
    ]

    deps = [
      "//flutter/third_party/dart/runtime/bin:gen_snapshot($host_toolchain)",
    ]

    if (host_os == "mac") {
      deps += [ ":ohos_entitlement_config" ]
      files += [
        {
          source = "$target_gen_dir/ohos_entitlements.txt"
          destination = "entitlements.txt"
        },
      ]
    }
  }
}

if (target_cpu == "x64" || target_cpu == "arm64") {
  zip_bundle("analyze_snapshot") {
    deps = [ "//flutter/third_party/dart/runtime/bin:analyze_snapshot($host_toolchain)" ]

    analyze_snapshot_bin = "analyze_snapshot"
    analyze_snapshot_out_dir = get_label_info(
            "//flutter/third_party/dart/runtime/bin:analyze_snapshot($host_toolchain)",
            "root_out_dir")
    analyze_snapshot_path =
        rebase_path("$analyze_snapshot_out_dir/$analyze_snapshot_bin")

    if (host_os == "linux") {
      output = "$ohos_zip_archive_dir/analyze-snapshot-linux-x64.zip"
    } else if (host_os == "mac") {
      output = "$ohos_zip_archive_dir/analyze-snapshot-darwin-x64.zip"
    } else if (host_os == "win") {
      output = "$ohos_zip_archive_dir/analyze-snapshot-windows-x64.zip"
      analyze_snapshot_bin = "analyze-snapshot.exe"
      analyze_snapshot_path = rebase_path("$root_out_dir/$analyze_snapshot_bin")
    }

    files = [
      {
        source = analyze_snapshot_path
        destination = analyze_snapshot_bin
      },
    ]
  }

  # TODO(godofredoc): Remove analyze_snapshot and rename new_analyze_snapshot when v2 migration is complete.
  # BUG: https://github.com/flutter/flutter/issues/105351
  zip_bundle("new_analyze_snapshot") {
    deps = [ "//flutter/third_party/dart/runtime/bin:analyze_snapshot($host_toolchain)" ]

    analyze_snapshot_bin = "analyze_snapshot"
    analyze_snapshot_out_dir = get_label_info(
            "//flutter/third_party/dart/runtime/bin:analyze_snapshot($host_toolchain)",
            "root_out_dir")
    analyze_snapshot_path =
        rebase_path("$analyze_snapshot_out_dir/$analyze_snapshot_bin")

    if (host_os == "linux") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/analyze-snapshot-linux-x64.zip"
    } else if (host_os == "mac") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/analyze-snapshot-darwin-x64.zip"
    } else if (host_os == "win") {
      output = "$ohos_zip_archive_dir/$full_platform_name-$flutter_runtime_mode/analyze-snapshot-windows-x64.zip"
      analyze_snapshot_bin = "analyze-snapshot.exe"
      analyze_snapshot_path = rebase_path("$root_out_dir/$analyze_snapshot_bin")
    }

    files = [
      {
        source = analyze_snapshot_path
        destination = analyze_snapshot_bin
      },
    ]
  }
}
